### ISSUE TITLE
Cannot buffer any npmjs.org package

### ISSUE THREAD

**Issue by oncletom** [bufferapp/buffer-chrome#12]
Hello,

# Thank You

first of all, thank you for the Chrome Extension. It is pretty handy to buffer anything browsable page :-)

# Use Case

Almost, as I encounter today, I cannot buffer any module on the npmjs.org website due to its CSP Policy.

In my DevTools console on https://www.npmjs.org/package/helmet after pressing the Buffer icon:

> Refused to frame 'https://d3ijcis4e2ziok.cloudfront.net/tpc-check.html' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
> Refused to frame 'https://bufferapp.com/add/?url=https%3A%2F%2Fwww.npmjs.org%2Fpackage%2Fhelmet&text=helmet&version=2.3.34&placement=toolbar&client_assistance=1' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

# Problem

- the UI stalls in an incomplete state, which makes it mandatory to reload the page to make it usable again
- there is no user facing error indicating this page cannot be buffered because of something broken behind the hood

![buffer-npmjs](https://cloud.githubusercontent.com/assets/138627/2614866/34593d62-bbf0-11e3-909d-eadf13e37fde.png)

# Solutions

- avoiding a broken UI on error
- be able to make it working on CSP enforced websites (how? This is another good question :-p)

**Comment by brentvatne** [comment]
@djfarrelly - did you end up finding a better solution?

**Comment by djfarrelly** [comment]
Hey @brentvatne - Sadly, we didn't find a better solution yet! I tried [injecting a local iframe then injecting our iframe](https://github.com/bufferapp/buffer-extension-shared/blob/master/nested-iframe.js) into that one and it worked, but created another layer to send postMessages. I think this approach didn't work in Firefox though. We were thinking about moving away from the iframe approach at some point in the future which would solve this once and for all, but we haven't started that project yet! Do you have any further insight into another solution? :smile:
