### ISSUE TITLE
URL gets scrambled with `%7B"data":null,"type":"buffer_3pc_done"%7D`

### ISSUE THREAD

**Issue by oncletom** [bufferapp/buffer-chrome#23]
It happens only on a specific website which then turns into a 404:

![screen shot 2015-10-05 at 10 02 14](https://cloud.githubusercontent.com/assets/138627/10276571/34696d64-6b48-11e5-9ecf-70bfb945586a.png)

When I disable Buffer, all is good.

PS: I also use Ghostery, in case it can be a combined side effect.

**Comment by karameloso** [comment]
This is still happening, any ideas?

**Comment by DavidDurman** [comment]
This is happening for our customers at https://appmixer.com when they have the Buffer Chrome extension enabled:
<img width="1389" alt="screen shot 2017-03-14 at 20 10 20" src="https://cloud.githubusercontent.com/assets/125717/23918213/5e6cfc86-08f2-11e7-85e8-ac213222af8a.png">

Disabling the extension fixes the problem. Is there a solution?

**Comment by mbootsman** [comment]
This is happening here too.

**Comment by danielmunoz** [comment]
This is happening for me too, when using Ghostery in Chrome. I tried to "solve it" by placing the following URLs in Ghostery white lists, without success:

bufferapp.com
buffer.com
