### ISSUE TITLE
Chrome Buffer extension totally useless for Twitter

### ISSUE THREAD

**Issue by AndreaPi** [bufferapp/buffer-chrome#32]
The retweet icon doesn't show up under tweets anymore. 
![image](https://user-images.githubusercontent.com/8233615/76681245-4d805080-65f1-11ea-8c3a-0d656344f78d.png)

As such, the extension is basically useless.

Chrome version: 
Version 80.0.3987.132 (Official Build) (64-bit)
OS: 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by patcon** [comment]
It's just focussed tweets that don't match css selectors anymore. Still works for lists like replies, and for a work-around, you can still use buffer ext if you just copy a part of tweet and search: https://twitter.com/search?q=sad%20to%20have%20had%20to%20cancel%20our%20Chicago%20R%20Collab%20this%20wknd&src=typed_query&f=live

And YES, I agree a fix is 100% better, but overstatements like "totally useless" feel too easy

**Comment by patcon** [comment]
also, alt+b or option+b (osx) still work :)

**Comment by AndreaPi** [comment]
It seems to work again now (I don't know what you mean by "focussed tweets", but it works for pinned tweets), so I'll close the issue for now.

**Comment by patcon** [comment]
Heh but no, you're right about it being partially broken :) only for these "focussed tweet" pages (but not for "listed" tweets like threads or search results):

https://twitter.com/EmilyRiederer/status/1238789723503710208

**Comment by AndreaPi** [comment]
If I click on the link you included, now I can see the "Send to Buffer" button which I couldn't see last year:

![image](https://user-images.githubusercontent.com/8233615/110484725-37fe1380-80eb-11eb-9485-7760cd31ec7a.png)

so...it seems to work now I guess?

**Comment by patcon** [comment]
Oh! Wasn't working yesterday, but maybe they fixed ..! (Or maybe it's just chrome or a conflicting plugin we both used)

Thanks though -- I'll dig back in a figure root cause
